# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ACMSolver.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ACMSolver.proto',
  package='ACMSolver',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x41\x43MSolver.proto\x12\tACMSolver\"\xa7\x02\n\nASCampaign\x12\x12\n\nproblem_id\x18\x01 \x01(\t\x12\x1c\n\x14original_campaign_id\x18\x02 \x01(\x05\x12\x12\n\nis_network\x18\n \x01(\x08\x12\x12\n\nstart_date\x18\x03 \x01(\x05\x12\x14\n\x0c\x65xpired_date\x18\x04 \x01(\x05\x12\x10\n\x08priority\x18\x05 \x01(\x05\x12\x0c\n\x04type\x18\x06 \x01(\x05\x12\r\n\x05total\x18\x07 \x01(\x05\x12\x15\n\tplace_ids\x18\x08 \x03(\x05\x42\x02\x10\x01\x12\x33\n\x07weights\x18\t \x03(\x0b\x32\".ACMSolver.ASCampaign.WeightsEntry\x1a.\n\x0cWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xe5\x01\n\x0b\x41SPlaceStat\x12\x12\n\nproblem_id\x18\x01 \x01(\t\x12\x19\n\x11original_place_id\x18\x02 \x01(\x05\x12.\n\x04\x63trs\x18\x03 \x03(\x0b\x32 .ACMSolver.ASPlaceStat.CtrsEntry\x12.\n\x0eprofiles_ratio\x18\x04 \x03(\x0b\x32\x16.ACMSolver.ProfileType\x12\x1a\n\x0e\x65stimate_views\x18\x05 \x03(\x05\x42\x02\x10\x01\x1a+\n\tCtrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"0\n\x0bProfileType\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x13\n\x07\x64\x65tails\x18\x02 \x03(\x02\x42\x02\x10\x01\"a\n\x08\x41SResult\x12\x12\n\nproblem_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61mpaign_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\x05\x12\x10\n\x08place_id\x18\x04 \x01(\x03\x12\x0c\n\x04view\x18\x05 \x01(\x02\"\x1f\n\tSetResult\x12\x12\n\nset_result\x18\x01 \x01(\x08\"*\n\tShareRate\x12\x12\n\nproblem_id\x18\x01 \x01(\t\x12\t\n\x01r\x18\x02 \x01(\x02\x32\x8f\x02\n\tACMSolver\x12=\n\tSetPlaces\x12\x16.ACMSolver.ASPlaceStat\x1a\x14.ACMSolver.SetResult\"\x00(\x01\x12<\n\x0cSetShareRate\x12\x14.ACMSolver.ShareRate\x1a\x14.ACMSolver.SetResult\"\x00\x12>\n\x0bSetCampaign\x12\x15.ACMSolver.ASCampaign\x1a\x14.ACMSolver.SetResult\"\x00(\x01\x12\x45\n\x12SetNetworkCampaign\x12\x15.ACMSolver.ASCampaign\x1a\x14.ACMSolver.SetResult\"\x00(\x01\x62\x06proto3'
)




_ASCAMPAIGN_WEIGHTSENTRY = _descriptor.Descriptor(
  name='WeightsEntry',
  full_name='ACMSolver.ASCampaign.WeightsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ACMSolver.ASCampaign.WeightsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ACMSolver.ASCampaign.WeightsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=326,
)

_ASCAMPAIGN = _descriptor.Descriptor(
  name='ASCampaign',
  full_name='ACMSolver.ASCampaign',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='problem_id', full_name='ACMSolver.ASCampaign.problem_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='original_campaign_id', full_name='ACMSolver.ASCampaign.original_campaign_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_network', full_name='ACMSolver.ASCampaign.is_network', index=2,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='ACMSolver.ASCampaign.start_date', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expired_date', full_name='ACMSolver.ASCampaign.expired_date', index=4,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='ACMSolver.ASCampaign.priority', index=5,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='ACMSolver.ASCampaign.type', index=6,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='ACMSolver.ASCampaign.total', index=7,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='place_ids', full_name='ACMSolver.ASCampaign.place_ids', index=8,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights', full_name='ACMSolver.ASCampaign.weights', index=9,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ASCAMPAIGN_WEIGHTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=326,
)


_ASPLACESTAT_CTRSENTRY = _descriptor.Descriptor(
  name='CtrsEntry',
  full_name='ACMSolver.ASPlaceStat.CtrsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ACMSolver.ASPlaceStat.CtrsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ACMSolver.ASPlaceStat.CtrsEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=558,
)

_ASPLACESTAT = _descriptor.Descriptor(
  name='ASPlaceStat',
  full_name='ACMSolver.ASPlaceStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='problem_id', full_name='ACMSolver.ASPlaceStat.problem_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='original_place_id', full_name='ACMSolver.ASPlaceStat.original_place_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctrs', full_name='ACMSolver.ASPlaceStat.ctrs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profiles_ratio', full_name='ACMSolver.ASPlaceStat.profiles_ratio', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='estimate_views', full_name='ACMSolver.ASPlaceStat.estimate_views', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ASPLACESTAT_CTRSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=558,
)


_PROFILETYPE = _descriptor.Descriptor(
  name='ProfileType',
  full_name='ACMSolver.ProfileType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ACMSolver.ProfileType.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='ACMSolver.ProfileType.details', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=608,
)


_ASRESULT = _descriptor.Descriptor(
  name='ASResult',
  full_name='ACMSolver.ASResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='problem_id', full_name='ACMSolver.ASResult.problem_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='campaign_id', full_name='ACMSolver.ASResult.campaign_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='ACMSolver.ASResult.date', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='place_id', full_name='ACMSolver.ASResult.place_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='view', full_name='ACMSolver.ASResult.view', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=610,
  serialized_end=707,
)


_SETRESULT = _descriptor.Descriptor(
  name='SetResult',
  full_name='ACMSolver.SetResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_result', full_name='ACMSolver.SetResult.set_result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=709,
  serialized_end=740,
)


_SHARERATE = _descriptor.Descriptor(
  name='ShareRate',
  full_name='ACMSolver.ShareRate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='problem_id', full_name='ACMSolver.ShareRate.problem_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r', full_name='ACMSolver.ShareRate.r', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=742,
  serialized_end=784,
)

_ASCAMPAIGN_WEIGHTSENTRY.containing_type = _ASCAMPAIGN
_ASCAMPAIGN.fields_by_name['weights'].message_type = _ASCAMPAIGN_WEIGHTSENTRY
_ASPLACESTAT_CTRSENTRY.containing_type = _ASPLACESTAT
_ASPLACESTAT.fields_by_name['ctrs'].message_type = _ASPLACESTAT_CTRSENTRY
_ASPLACESTAT.fields_by_name['profiles_ratio'].message_type = _PROFILETYPE
DESCRIPTOR.message_types_by_name['ASCampaign'] = _ASCAMPAIGN
DESCRIPTOR.message_types_by_name['ASPlaceStat'] = _ASPLACESTAT
DESCRIPTOR.message_types_by_name['ProfileType'] = _PROFILETYPE
DESCRIPTOR.message_types_by_name['ASResult'] = _ASRESULT
DESCRIPTOR.message_types_by_name['SetResult'] = _SETRESULT
DESCRIPTOR.message_types_by_name['ShareRate'] = _SHARERATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ASCampaign = _reflection.GeneratedProtocolMessageType('ASCampaign', (_message.Message,), {

  'WeightsEntry' : _reflection.GeneratedProtocolMessageType('WeightsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ASCAMPAIGN_WEIGHTSENTRY,
    '__module__' : 'ACMSolver_pb2'
    # @@protoc_insertion_point(class_scope:ACMSolver.ASCampaign.WeightsEntry)
    })
  ,
  'DESCRIPTOR' : _ASCAMPAIGN,
  '__module__' : 'ACMSolver_pb2'
  # @@protoc_insertion_point(class_scope:ACMSolver.ASCampaign)
  })
_sym_db.RegisterMessage(ASCampaign)
_sym_db.RegisterMessage(ASCampaign.WeightsEntry)

ASPlaceStat = _reflection.GeneratedProtocolMessageType('ASPlaceStat', (_message.Message,), {

  'CtrsEntry' : _reflection.GeneratedProtocolMessageType('CtrsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ASPLACESTAT_CTRSENTRY,
    '__module__' : 'ACMSolver_pb2'
    # @@protoc_insertion_point(class_scope:ACMSolver.ASPlaceStat.CtrsEntry)
    })
  ,
  'DESCRIPTOR' : _ASPLACESTAT,
  '__module__' : 'ACMSolver_pb2'
  # @@protoc_insertion_point(class_scope:ACMSolver.ASPlaceStat)
  })
_sym_db.RegisterMessage(ASPlaceStat)
_sym_db.RegisterMessage(ASPlaceStat.CtrsEntry)

ProfileType = _reflection.GeneratedProtocolMessageType('ProfileType', (_message.Message,), {
  'DESCRIPTOR' : _PROFILETYPE,
  '__module__' : 'ACMSolver_pb2'
  # @@protoc_insertion_point(class_scope:ACMSolver.ProfileType)
  })
_sym_db.RegisterMessage(ProfileType)

ASResult = _reflection.GeneratedProtocolMessageType('ASResult', (_message.Message,), {
  'DESCRIPTOR' : _ASRESULT,
  '__module__' : 'ACMSolver_pb2'
  # @@protoc_insertion_point(class_scope:ACMSolver.ASResult)
  })
_sym_db.RegisterMessage(ASResult)

SetResult = _reflection.GeneratedProtocolMessageType('SetResult', (_message.Message,), {
  'DESCRIPTOR' : _SETRESULT,
  '__module__' : 'ACMSolver_pb2'
  # @@protoc_insertion_point(class_scope:ACMSolver.SetResult)
  })
_sym_db.RegisterMessage(SetResult)

ShareRate = _reflection.GeneratedProtocolMessageType('ShareRate', (_message.Message,), {
  'DESCRIPTOR' : _SHARERATE,
  '__module__' : 'ACMSolver_pb2'
  # @@protoc_insertion_point(class_scope:ACMSolver.ShareRate)
  })
_sym_db.RegisterMessage(ShareRate)


_ASCAMPAIGN_WEIGHTSENTRY._options = None
_ASCAMPAIGN.fields_by_name['place_ids']._options = None
_ASPLACESTAT_CTRSENTRY._options = None
_ASPLACESTAT.fields_by_name['estimate_views']._options = None
_PROFILETYPE.fields_by_name['details']._options = None

_ACMSOLVER = _descriptor.ServiceDescriptor(
  name='ACMSolver',
  full_name='ACMSolver.ACMSolver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=787,
  serialized_end=1058,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetPlaces',
    full_name='ACMSolver.ACMSolver.SetPlaces',
    index=0,
    containing_service=None,
    input_type=_ASPLACESTAT,
    output_type=_SETRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetShareRate',
    full_name='ACMSolver.ACMSolver.SetShareRate',
    index=1,
    containing_service=None,
    input_type=_SHARERATE,
    output_type=_SETRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetCampaign',
    full_name='ACMSolver.ACMSolver.SetCampaign',
    index=2,
    containing_service=None,
    input_type=_ASCAMPAIGN,
    output_type=_SETRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetNetworkCampaign',
    full_name='ACMSolver.ACMSolver.SetNetworkCampaign',
    index=3,
    containing_service=None,
    input_type=_ASCAMPAIGN,
    output_type=_SETRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACMSOLVER)

DESCRIPTOR.services_by_name['ACMSolver'] = _ACMSOLVER

# @@protoc_insertion_point(module_scope)
